export default [
    {
        login: "boraacici",
        id: 26149034,
        node_id: "MDQ6VXNlcjI2MTQ5MDM0",
        avatar_url: "https://avatars.githubusercontent.com/u/26149034?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/boraacici",
        html_url: "https://github.com/boraacici",
        followers_url: "https://api.github.com/users/boraacici/followers",
        following_url: "https://api.github.com/users/boraacici/following{/other_user}",
        gists_url: "https://api.github.com/users/boraacici/gists{/gist_id}",
        starred_url: "https://api.github.com/users/boraacici/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/boraacici/subscriptions",
        organizations_url: "https://api.github.com/users/boraacici/orgs",
        repos_url: "https://api.github.com/users/boraacici/repos",
        events_url: "https://api.github.com/users/boraacici/events{/privacy}",
        received_events_url: "https://api.github.com/users/boraacici/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "yunusdonmez",
        id: 18112932,
        node_id: "MDQ6VXNlcjE4MTEyOTMy",
        avatar_url: "https://avatars.githubusercontent.com/u/18112932?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yunusdonmez",
        html_url: "https://github.com/yunusdonmez",
        followers_url: "https://api.github.com/users/yunusdonmez/followers",
        following_url: "https://api.github.com/users/yunusdonmez/following{/other_user}",
        gists_url: "https://api.github.com/users/yunusdonmez/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yunusdonmez/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yunusdonmez/subscriptions",
        organizations_url: "https://api.github.com/users/yunusdonmez/orgs",
        repos_url: "https://api.github.com/users/yunusdonmez/repos",
        events_url: "https://api.github.com/users/yunusdonmez/events{/privacy}",
        received_events_url: "https://api.github.com/users/yunusdonmez/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "alisentas",
        id: 3109558,
        node_id: "MDQ6VXNlcjMxMDk1NTg=",
        avatar_url: "https://avatars.githubusercontent.com/u/3109558?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/alisentas",
        html_url: "https://github.com/alisentas",
        followers_url: "https://api.github.com/users/alisentas/followers",
        following_url: "https://api.github.com/users/alisentas/following{/other_user}",
        gists_url: "https://api.github.com/users/alisentas/gists{/gist_id}",
        starred_url: "https://api.github.com/users/alisentas/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/alisentas/subscriptions",
        organizations_url: "https://api.github.com/users/alisentas/orgs",
        repos_url: "https://api.github.com/users/alisentas/repos",
        events_url: "https://api.github.com/users/alisentas/events{/privacy}",
        received_events_url: "https://api.github.com/users/alisentas/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "uguravci",
        id: 16518892,
        node_id: "MDQ6VXNlcjE2NTE4ODky",
        avatar_url: "https://avatars.githubusercontent.com/u/16518892?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/uguravci",
        html_url: "https://github.com/uguravci",
        followers_url: "https://api.github.com/users/uguravci/followers",
        following_url: "https://api.github.com/users/uguravci/following{/other_user}",
        gists_url: "https://api.github.com/users/uguravci/gists{/gist_id}",
        starred_url: "https://api.github.com/users/uguravci/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/uguravci/subscriptions",
        organizations_url: "https://api.github.com/users/uguravci/orgs",
        repos_url: "https://api.github.com/users/uguravci/repos",
        events_url: "https://api.github.com/users/uguravci/events{/privacy}",
        received_events_url: "https://api.github.com/users/uguravci/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "furkansekerci",
        id: 30621367,
        node_id: "MDQ6VXNlcjMwNjIxMzY3",
        avatar_url: "https://avatars.githubusercontent.com/u/30621367?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/furkansekerci",
        html_url: "https://github.com/furkansekerci",
        followers_url: "https://api.github.com/users/furkansekerci/followers",
        following_url: "https://api.github.com/users/furkansekerci/following{/other_user}",
        gists_url: "https://api.github.com/users/furkansekerci/gists{/gist_id}",
        starred_url: "https://api.github.com/users/furkansekerci/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/furkansekerci/subscriptions",
        organizations_url: "https://api.github.com/users/furkansekerci/orgs",
        repos_url: "https://api.github.com/users/furkansekerci/repos",
        events_url: "https://api.github.com/users/furkansekerci/events{/privacy}",
        received_events_url: "https://api.github.com/users/furkansekerci/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "mtnmunuklu",
        id: 31629207,
        node_id: "MDQ6VXNlcjMxNjI5MjA3",
        avatar_url: "https://avatars.githubusercontent.com/u/31629207?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/mtnmunuklu",
        html_url: "https://github.com/mtnmunuklu",
        followers_url: "https://api.github.com/users/mtnmunuklu/followers",
        following_url: "https://api.github.com/users/mtnmunuklu/following{/other_user}",
        gists_url: "https://api.github.com/users/mtnmunuklu/gists{/gist_id}",
        starred_url: "https://api.github.com/users/mtnmunuklu/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/mtnmunuklu/subscriptions",
        organizations_url: "https://api.github.com/users/mtnmunuklu/orgs",
        repos_url: "https://api.github.com/users/mtnmunuklu/repos",
        events_url: "https://api.github.com/users/mtnmunuklu/events{/privacy}",
        received_events_url: "https://api.github.com/users/mtnmunuklu/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "AnilFurkanOkcun",
        id: 33378423,
        node_id: "MDQ6VXNlcjMzMzc4NDIz",
        avatar_url: "https://avatars.githubusercontent.com/u/33378423?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/AnilFurkanOkcun",
        html_url: "https://github.com/AnilFurkanOkcun",
        followers_url: "https://api.github.com/users/AnilFurkanOkcun/followers",
        following_url: "https://api.github.com/users/AnilFurkanOkcun/following{/other_user}",
        gists_url: "https://api.github.com/users/AnilFurkanOkcun/gists{/gist_id}",
        starred_url: "https://api.github.com/users/AnilFurkanOkcun/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/AnilFurkanOkcun/subscriptions",
        organizations_url: "https://api.github.com/users/AnilFurkanOkcun/orgs",
        repos_url: "https://api.github.com/users/AnilFurkanOkcun/repos",
        events_url: "https://api.github.com/users/AnilFurkanOkcun/events{/privacy}",
        received_events_url: "https://api.github.com/users/AnilFurkanOkcun/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "melekpzr",
        id: 43832745,
        node_id: "MDQ6VXNlcjQzODMyNzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/43832745?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/melekpzr",
        html_url: "https://github.com/melekpzr",
        followers_url: "https://api.github.com/users/melekpzr/followers",
        following_url: "https://api.github.com/users/melekpzr/following{/other_user}",
        gists_url: "https://api.github.com/users/melekpzr/gists{/gist_id}",
        starred_url: "https://api.github.com/users/melekpzr/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/melekpzr/subscriptions",
        organizations_url: "https://api.github.com/users/melekpzr/orgs",
        repos_url: "https://api.github.com/users/melekpzr/repos",
        events_url: "https://api.github.com/users/melekpzr/events{/privacy}",
        received_events_url: "https://api.github.com/users/melekpzr/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "brkmustu",
        id: 47041552,
        node_id: "MDQ6VXNlcjQ3MDQxNTUy",
        avatar_url: "https://avatars.githubusercontent.com/u/47041552?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/brkmustu",
        html_url: "https://github.com/brkmustu",
        followers_url: "https://api.github.com/users/brkmustu/followers",
        following_url: "https://api.github.com/users/brkmustu/following{/other_user}",
        gists_url: "https://api.github.com/users/brkmustu/gists{/gist_id}",
        starred_url: "https://api.github.com/users/brkmustu/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/brkmustu/subscriptions",
        organizations_url: "https://api.github.com/users/brkmustu/orgs",
        repos_url: "https://api.github.com/users/brkmustu/repos",
        events_url: "https://api.github.com/users/brkmustu/events{/privacy}",
        received_events_url: "https://api.github.com/users/brkmustu/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "msahinciftci",
        id: 14074488,
        node_id: "MDQ6VXNlcjE0MDc0NDg4",
        avatar_url: "https://avatars.githubusercontent.com/u/14074488?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/msahinciftci",
        html_url: "https://github.com/msahinciftci",
        followers_url: "https://api.github.com/users/msahinciftci/followers",
        following_url: "https://api.github.com/users/msahinciftci/following{/other_user}",
        gists_url: "https://api.github.com/users/msahinciftci/gists{/gist_id}",
        starred_url: "https://api.github.com/users/msahinciftci/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/msahinciftci/subscriptions",
        organizations_url: "https://api.github.com/users/msahinciftci/orgs",
        repos_url: "https://api.github.com/users/msahinciftci/repos",
        events_url: "https://api.github.com/users/msahinciftci/events{/privacy}",
        received_events_url: "https://api.github.com/users/msahinciftci/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "suleymanlimann",
        id: 23210013,
        node_id: "MDQ6VXNlcjIzMjEwMDEz",
        avatar_url: "https://avatars.githubusercontent.com/u/23210013?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/suleymanlimann",
        html_url: "https://github.com/suleymanlimann",
        followers_url: "https://api.github.com/users/suleymanlimann/followers",
        following_url: "https://api.github.com/users/suleymanlimann/following{/other_user}",
        gists_url: "https://api.github.com/users/suleymanlimann/gists{/gist_id}",
        starred_url: "https://api.github.com/users/suleymanlimann/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/suleymanlimann/subscriptions",
        organizations_url: "https://api.github.com/users/suleymanlimann/orgs",
        repos_url: "https://api.github.com/users/suleymanlimann/repos",
        events_url: "https://api.github.com/users/suleymanlimann/events{/privacy}",
        received_events_url: "https://api.github.com/users/suleymanlimann/received_events",
        type: "User",
        site_admin: false
    },
    {
        login: "CnytSntrk",
        id: 19299981,
        node_id: "MDQ6VXNlcjE5Mjk5OTgx",
        avatar_url: "https://avatars.githubusercontent.com/u/19299981?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/CnytSntrk",
        html_url: "https://github.com/CnytSntrk",
        followers_url: "https://api.github.com/users/CnytSntrk/followers",
        following_url: "https://api.github.com/users/CnytSntrk/following{/other_user}",
        gists_url: "https://api.github.com/users/CnytSntrk/gists{/gist_id}",
        starred_url: "https://api.github.com/users/CnytSntrk/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/CnytSntrk/subscriptions",
        organizations_url: "https://api.github.com/users/CnytSntrk/orgs",
        repos_url: "https://api.github.com/users/CnytSntrk/repos",
        events_url: "https://api.github.com/users/CnytSntrk/events{/privacy}",
        received_events_url: "https://api.github.com/users/CnytSntrk/received_events",
        type: "User",
        site_admin: false
    }
];
