export default {
    login: "ogzhnmvsm",
    id: 28672471,
    node_id: "MDQ6VXNlcjI4NjcyNDcx",
    avatar_url: "https://avatars.githubusercontent.com/u/28672471?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ogzhnmvsm",
    html_url: "https://github.com/ogzhnmvsm",
    followers_url: "https://api.github.com/users/ogzhnmvsm/followers",
    following_url: "https://api.github.com/users/ogzhnmvsm/following{/other_user}",
    gists_url: "https://api.github.com/users/ogzhnmvsm/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ogzhnmvsm/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ogzhnmvsm/subscriptions",
    organizations_url: "https://api.github.com/users/ogzhnmvsm/orgs",
    repos_url: "https://api.github.com/users/ogzhnmvsm/repos",
    events_url: "https://api.github.com/users/ogzhnmvsm/events{/privacy}",
    received_events_url: "https://api.github.com/users/ogzhnmvsm/received_events",
    type: "User",
    site_admin: false,
    name: "Oğuzhan Mevsim",
    company: "Dataeva",
    blog: "https://ogzhnmvsm.github.io/",
    location: "Turkey",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: "oguzhanmevsim",
    public_repos: 8,
    public_gists: 0,
    followers: 12,
    following: 12,
    created_at: "2017-05-13T12:58:36Z",
    updated_at: "2021-04-30T23:34:18Z"
};
